---
title: "Percentage of westerns each year?"
author: "Mariama Jaiteh"
date: "4/6/2017"
output: html_document
---

##Load Library & connect to database
```{r message=FALSE}
library(mdsr)
library(RMySQL)
db <- dbConnect_scidb(dbname = "imdb")
```

## Create a connection
```{r message=FALSE}
class(db)
```

##Total movies 
```{r message=FALSE}

films <- db %>% 
  dbGetQuery("SELECT production_year, COUNT(*) as num_films
FROM imdb.title
WHERE kind_id = 1
GROUP BY production_year;")
```

#Total western movies
```{r message=FALSE}
west_films <- db %>% 
  dbGetQuery("SELECT production_year, COUNT(*) as western_films
FROM imdb.movie_info
JOIN title ON movie_info.movie_id = title.id 
WHERE info_type_id = 3
AND info LIKE '%Western%'
AND kind_id = 1
GROUP BY production_year;")
```

#Join total films and westerns data frame
```{r message=FALSE}
#Join two data frames
movies <- films %>%
  left_join(west_films, by="production_year")

#Replace NA values with zeros
na.zero <- function (x) {
    x[is.na(x)] <- 0
    return(x)
}
movies <- na.zero(movies)
#Remove rows that don't make sense to plot.
movies <- movies[-c(1,139,140,141,142,143,144), ]

```
#Plot the percentage of western films each year
```{r message=FALSE}
ggplot(movies, aes(x=production_year,y=(western_films/num_films)*100)) + geom_line() + ylab("Percentage of Western Movies")+ scale_x_continuous("Year",breaks=c(1900,1920,1940,1960,1980,2000,2020)) +  annotate("pointrange", x = 1992, y = 0.25, ymin = 0, ymax = 0,
  colour = "red", size = 0.2) + annotate("text", x = 1992, y = 0.65, label = "Unforgiven")

```
